# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMAccountBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMAccountBook
  pod 'SnapKit'
  pod 'FMDB'
  pod 'Kingfisher'
  pod 'KafkaRefresh'
  
  # 数据库调试
  pod 'DatabaseVisual', :git => 'https://github.com/FMYang/DatabaseVisual.git'

end
